/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package las28creencias;

import java.awt.Color;
import javax.swing.DefaultListModel;
/**
 *
 * @author LDS
 */
public class Ventana extends javax.swing.JFrame {

    Metodos operacion = new Metodos();
    DefaultListModel Lista;
    public Ventana() {
        getContentPane().setBackground(Color.white);
        initComponents();
        operacion.agregar();
        Lista = new DefaultListModel();
        jList1.setModel(Lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("creencias de La Iglesia Adventista");
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("ORDEN");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("DESORDEN");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("MOSTRAR CREENCIAS EN ");
        jLabel29.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.black));
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jList1.setBackground(new java.awt.Color(255, 255, 153));
        jList1.setForeground(new java.awt.Color(0, 153, 153));
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel1.setText("Las 28 Creencias De ");

        jLabel2.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel2.setText("la  Iglesia Adventista  Del Séptimo Día");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Lista.clear();
        Lista.addElement(operacion.ordenarCreencias(0));
        Lista.addElement(operacion.ordenarCreencias(1));
        Lista.addElement(operacion.ordenarCreencias(2));
        Lista.addElement(operacion.ordenarCreencias(3));
        Lista.addElement(operacion.ordenarCreencias(4));
        Lista.addElement(operacion.ordenarCreencias(5));
        Lista.addElement(operacion.ordenarCreencias(6));
        Lista.addElement(operacion.ordenarCreencias(7));
        Lista.addElement(operacion.ordenarCreencias(8));
        Lista.addElement(operacion.ordenarCreencias(9));
        Lista.addElement(operacion.ordenarCreencias(10));
        Lista.addElement(operacion.ordenarCreencias(11));
        Lista.addElement(operacion.ordenarCreencias(12));
        Lista.addElement(operacion.ordenarCreencias(13));
        Lista.addElement(operacion.ordenarCreencias(14));
        Lista.addElement(operacion.ordenarCreencias(15));
        Lista.addElement(operacion.ordenarCreencias(16));
        Lista.addElement(operacion.ordenarCreencias(17));
        Lista.addElement(operacion.ordenarCreencias(18));
        Lista.addElement(operacion.ordenarCreencias(19));
        Lista.addElement(operacion.ordenarCreencias(20));
        Lista.addElement(operacion.ordenarCreencias(21));
        Lista.addElement(operacion.ordenarCreencias(22));
        Lista.addElement(operacion.ordenarCreencias(23));
        Lista.addElement(operacion.ordenarCreencias(24));
        Lista.addElement(operacion.ordenarCreencias(25));
        Lista.addElement(operacion.ordenarCreencias(26));
        Lista.addElement(operacion.ordenarCreencias(27));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Lista.clear();
        Lista.addElement(operacion.desordenarCreencias(0));
        Lista.addElement(operacion.desordenarCreencias(1));
        Lista.addElement(operacion.desordenarCreencias(2));
        Lista.addElement(operacion.desordenarCreencias(3));
        Lista.addElement(operacion.desordenarCreencias(4));
        Lista.addElement(operacion.desordenarCreencias(5));
        Lista.addElement(operacion.desordenarCreencias(6));
        Lista.addElement(operacion.desordenarCreencias(7));
        Lista.addElement(operacion.desordenarCreencias(8));
        Lista.addElement(operacion.desordenarCreencias(9));
        Lista.addElement(operacion.desordenarCreencias(10));
        Lista.addElement(operacion.desordenarCreencias(11));
        Lista.addElement(operacion.desordenarCreencias(12));
        Lista.addElement(operacion.desordenarCreencias(13));
        Lista.addElement(operacion.desordenarCreencias(14));
        Lista.addElement(operacion.desordenarCreencias(15));
        Lista.addElement(operacion.desordenarCreencias(16));
        Lista.addElement(operacion.desordenarCreencias(17));
        Lista.addElement(operacion.desordenarCreencias(18));
        Lista.addElement(operacion.desordenarCreencias(19));
        Lista.addElement(operacion.desordenarCreencias(20));
        Lista.addElement(operacion.desordenarCreencias(21));
        Lista.addElement(operacion.desordenarCreencias(22));
        Lista.addElement(operacion.desordenarCreencias(23));
        Lista.addElement(operacion.desordenarCreencias(24));
        Lista.addElement(operacion.desordenarCreencias(25));
        Lista.addElement(operacion.desordenarCreencias(26));
        Lista.addElement(operacion.desordenarCreencias(27));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
